# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: home
    url: /
    weight: 10
  - name: topics
    url: tags/
    weight: 20
  - name: education
    url: education/
    weight: 30
